packages:
  - '.'

allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@next/eslint-plugin-next@16.3.0'
  - eslint-config-next@16.3.0
overrides:
  style-to-js: 2.0.2
